PATH_TO_DB_DIR = "../../data/database/"
PATH_TO_DB_PRICE_DATA = PATH_TO_DB_DIR + "price_data.db"
PATH_TO_DB_WITH_MOST_ACTIVE_STOCKS = PATH_TO_DB_DIR + "most_active_stocks.db"
PATH_TO_DB_WITH_YF_NEWS = PATH_TO_DB_DIR + "yf_news.db"
PATH_TO_DB_WITH_NEWS_API_ORG_NEWS = PATH_TO_DB_DIR + "news_api_org.db"
PATH_TO_DB_WITH_MODEL_PREDICTIONS = PATH_TO_DB_DIR + "model_predictions.db"

NEWS_API_TOP_BUSINESS_HEADLINES_TABLE_NAME = "top_business_headlines"

PATH_TO_RAW_DATA_DIR = "../../data/raw data/"
PATH_TO_CSV_WITH_S_AND_P_DATA = PATH_TO_RAW_DATA_DIR + "S&P 500 info.csv"
PATH_TO_CSV_WITH_MOST_ACTIVE_STOCKS = PATH_TO_RAW_DATA_DIR + "Most Active Stocks.csv"

MOST_ACTIVE_STOCKS_TABLE_NAME = "stocks"
PREDICTIONS_TABLE_NAME = "predictions"


PATH_TO_API_KEY_DIR = "../../API Keys/"


ALPHAVANTAGE_API_KEY_FILE_NAME = "alpha_vantage_api_key.txt"
NEWS_API_ORG_API_KEY_FILE_NAME = "news_api_org_api_key.txt"
GUARDIAN_NEWS_API_KEY_FILE_NAME = "guardian_news_api_key.txt"


PATH_TO_ALPHAVANTAGE_API_KEY = PATH_TO_API_KEY_DIR + ALPHAVANTAGE_API_KEY_FILE_NAME
PATH_TO_NEWS_API_ORG_API_KEY = PATH_TO_API_KEY_DIR + NEWS_API_ORG_API_KEY_FILE_NAME
PATH_TO_GUARDIAN_NEWS_API_KEY = PATH_TO_API_KEY_DIR + GUARDIAN_NEWS_API_KEY_FILE_NAME
